---
server:
  port: 4001
spring:
  profiles: dev
  application:
    name: microservice-config-dev
---
server:
  port: 4002
spring:
  profiles:
    active: prod
    application: microservice-config-prod
    